### ISSUE TITLE
Support creation by code

### ISSUE THREAD

**Issue by arrix** [823546371/PullToRefresh#10]
The layout can only be inflated from xml because some critical initialization is performed in onFinishInflate()

```
@Override
protected void onFinishInflate() {
    super.onFinishInflate();
    mChildView = getChildAt(0);
    addHeadView();
    addFooterView();
}
```
When I create the view hierarchy by code, for example, in anko layout DSL, it ends up with NullPointerException because mChild is never set.

Hopefully it's an easy fix :)

**Comment by 823546371** [comment]
thanks
