### ISSUE TITLE
【bug】1.2.6 设置自己的headview，然后刷新报错。

### ISSUE THREAD

**Issue by fly7632785** [823546371/PullToRefresh#9]
原因是因为   你setHeadView只是把成员变量进行了赋值而已，并没有执行addHeadView的方法，所以，现在的这个custom headview没有layoutParams ， onTouchEvent里面 你又用到了 layoutparam.height，直接空指针！

![1723b541-0d24-4ddd-80a2-6ec60022af43](https://user-images.githubusercontent.com/10276266/32532430-29fde718-c485-11e7-8807-6145270ed474.png)

![4ae911ea-83f0-4eb7-83cb-4c98c48f4076](https://user-images.githubusercontent.com/10276266/32532432-2e0bc6a4-c485-11e7-9036-e96590cdeb52.png)

**Comment by 823546371** [comment]
thanks
